### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by AmadeusLiz** [crist-12/teach.it#2]
Propuestas para logo de la app

**Comment by AmadeusLiz** [comment]
![LOGO2](https://user-images.githubusercontent.com/71053273/108938005-e8144c80-7614-11eb-9190-7e57d8dda4de.png)
![LOGO](https://user-images.githubusercontent.com/71053273/108938009-e8144c80-7614-11eb-9ee0-9bb555a3101a.png)
Por los momentos esto es lo que tengo pensado

**Comment by AmadeusLiz** [comment]
![New Project](https://user-images.githubusercontent.com/71053273/108938038-f6626880-7614-11eb-8150-61c56ec14b34.png)
![New Project(1)](https://user-images.githubusercontent.com/71053273/108938039-f6626880-7614-11eb-8db6-2ea3a472341a.png)
Podriamos igualmente solo usar las letras para que esté en la app y el logo solo de la T por aparte donde se requiera

**Comment by crist-12** [comment]
Me gusta el segundo, y que usemos la "T" por aparte como dice.

**Comment by Jeff1811-no** [comment]
También me quedo con el usamos la T, me parece mas bonito.

**Comment by AmadeusLiz** [comment]
Listo!
