### ISSUE TITLE
TutorSignUpForm : handlerCheck no actualiza al instante el estado de los checkboxes

### ISSUE THREAD

**Issue by AmadeusLiz** [crist-12/teach.it#5]
**Linea 74** en `TutorSignUpForm : handlerCheck`
El problema es manejar el estado de las categorias que se van seleccionando. Actualmente parece no funcionar bien del todo esta funcion implementada, parece que no toma efecto hasta luego de cierto tiempo, si le doy check a alguna categoria y vuelvo a presionar no cambia su estado, pero si escribo algo en otro de los inputs y regreso a tocar el check si cambia.
Asi que creo el cambio no esta tomando efecto inmediato, hay que revisar de que manera se puede resolver.

**Comment by Jeff1811-no** [comment]
Problema de handlerCheck arreglado, se cambio el checkBox por react-native-multiple-select-list  para poder darle multiples veces a la hora de cambiar de categoria.
